/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luismassaneiro.sistemadonai.view.operacoes;

import com.luismassaneiro.sistemadonai.controller.DAOFactory;
import com.luismassaneiro.sistemadonai.controller.PedidoDAO;
import com.luismassaneiro.sistemadonai.controller.PedidoItemDAO;
import com.luismassaneiro.sistemadonai.enums.MensagemFixas;
import com.luismassaneiro.sistemadonai.exceptions.ValidateException;
import com.luismassaneiro.sistemadonai.helper.PedidoHelper;
import com.luismassaneiro.sistemadonai.model.Cliente;
import com.luismassaneiro.sistemadonai.model.Pedido;
import com.luismassaneiro.sistemadonai.model.PedidoItem;
import com.luismassaneiro.sistemadonai.model.Produto;
import com.luismassaneiro.sistemadonai.utils.FormatUtils;
import com.luismassaneiro.sistemadonai.view.tablemodel.PedidoItemTableModel;
import com.luismassaneiro.sistemadonai.view.Selecionador;
import com.luismassaneiro.sistemadonai.view.cadastro.ClienteBrowser;
import com.luismassaneiro.sistemadonai.view.cadastro.ProdutoBrowser;
import com.luismassaneiro.sistemadonai.view.desktop.GerenciadorJanelas;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author luis.massaneiro
 */
public class PedidoForm extends javax.swing.JInternalFrame implements Selecionador<Object> {

    private Pedido pedido = new Pedido();
    private BigDecimal totalCompra = BigDecimal.ZERO;
    private BigDecimal totalRecebido = BigDecimal.ZERO;
    private static PedidoDAO pedidoDAO = DAOFactory.criaPedidoDAO();
    private static PedidoItemDAO pedidoItemDAO = DAOFactory.criaPedidoItemDAO();   
    private Produto produtoLookup;
    private Cliente clienteLookup;
    
    public PedidoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_PedidoItem = new javax.swing.JTable();
        botao_FinalizaPedido = new javax.swing.JButton();
        botao_CancelarPedido = new javax.swing.JButton();
        botao_ExcluirItem = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        texto_codigoCliente = new javax.swing.JTextField();
        texto_nomeCliente = new javax.swing.JTextField();
        botao_pesquisarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texto_codigoProduto = new javax.swing.JTextField();
        texto_descricaoProduto = new javax.swing.JTextField();
        botao_pesquisarProduto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        texto_quantidade = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        texto_observacao = new javax.swing.JTextField();
        botao_adicionarProduto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        texto_total = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pedido");

        tabela_PedidoItem.setModel(new PedidoItemTableModel());
        jScrollPane1.setViewportView(tabela_PedidoItem);

        botao_FinalizaPedido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botao_FinalizaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/seta.png"))); // NOI18N
        botao_FinalizaPedido.setText("Finalizar");
        botao_FinalizaPedido.setMaximumSize(new java.awt.Dimension(141, 41));
        botao_FinalizaPedido.setMinimumSize(new java.awt.Dimension(141, 41));
        botao_FinalizaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_FinalizaPedidoActionPerformed(evt);
            }
        });

        botao_CancelarPedido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botao_CancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/cancel-24.png"))); // NOI18N
        botao_CancelarPedido.setText("Cancelar");
        botao_CancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CancelarPedidoActionPerformed(evt);
            }
        });

        botao_ExcluirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/delete16.png"))); // NOI18N
        botao_ExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ExcluirItemActionPerformed(evt);
            }
        });

        jLabel12.setText("Cliente");

        texto_codigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_codigoClienteActionPerformed(evt);
            }
        });

        texto_nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_nomeClienteActionPerformed(evt);
            }
        });

        botao_pesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/search16.png"))); // NOI18N
        botao_pesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesquisarClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto");

        botao_pesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/search16.png"))); // NOI18N
        botao_pesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pesquisarProdutoActionPerformed(evt);
            }
        });

        jLabel10.setText("Quantidade");

        texto_quantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel13.setText("Observação");

        botao_adicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/plus-green16.png"))); // NOI18N
        botao_adicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_adicionarProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botao_ExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(texto_codigoProduto))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(texto_descricaoProduto))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(texto_codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(texto_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botao_pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botao_pesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texto_quantidade))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(texto_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(botao_adicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(botao_FinalizaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_CancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_total, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(texto_codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(texto_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botao_pesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(texto_codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(texto_descricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botao_pesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(texto_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(texto_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botao_adicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_ExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_CancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_FinalizaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_FinalizaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_FinalizaPedidoActionPerformed
        if(CollectionUtils.isNotEmpty(pedido.getItens())) {
//            try {
//                TipoFormaPagamento formaPagamentoSelecionada = (TipoFormaPagamento) combo_FormaPagamento.getSelectedItem();
//                if(TipoFormaPagamento.CARTAO.equals(formaPagamentoSelecionada) && StringUtils.isEmpty(texto_TotalRecebido.getText())) {
//                    JOptionPane.showMessageDialog(this, "O valor recebido não foi informado e a forma de pagamento foi por cartão. \nO valor recebido receberá o total da compra. ", "Informação", JOptionPane.INFORMATION_MESSAGE);
//                    texto_TotalRecebido.setText(texto_TotalCompra.getText());
//                }
//                pedido.setTipoFormaPagamento(formaPagamentoSelecionada);
//                pedido.setObservacao(textArea_Observacao.getText());
//                pedido.setValorAcrescimo(FormatUtils.parseBigDecimal(texto_Acrescimo.getText()));
//                pedido.setValorDesconto(FormatUtils.parseBigDecimal(texto_Desconto.getText()));
//                pedido.setValorPago(FormatUtils.parseBigDecimal(texto_TotalRecebido.getText()));
//                pedido.setValorTroco(FormatUtils.parseBigDecimal(texto_Troco.getText()));
//                pedido.setValorTotal(FormatUtils.parseBigDecimal(texto_TotalCompra.getText()));
//                BigDecimal valorLucro = recuperaValorLucro();
//                pedido.setValorLucro(valorLucro);
//                pedido.setPedidoFinalizado(true);
//                pedido = pedidoDAO.atualizar(pedido);
//                JOptionPane.showMessageDialog(this, "Pedido finalizado com sucesso!", "Finalização", JOptionPane.INFORMATION_MESSAGE);
//                limpar();
//            } catch(HeadlessException | ParseException | ValidateException e) {
//                Logger.getLogger(PedidoForm.class.getName()).log(Level.SEVERE, null, e);
//                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Não foi adicionado nenhum produto!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botao_FinalizaPedidoActionPerformed

    private void botao_CancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CancelarPedidoActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente efetuar o cancelamento?");
        if(resp == JOptionPane.YES_OPTION) {
            cancelaPedido();
        }
    }//GEN-LAST:event_botao_CancelarPedidoActionPerformed

    private void botao_ExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ExcluirItemActionPerformed
        PedidoItem pedidoItemExcluir = getPedidoItemSelecionado();
        if(pedidoItemExcluir == null) {
            JOptionPane.showMessageDialog(this, "Nenhum item foi selecionado", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
               // ProdutoHelper.getInstance().atualizaQuantidadeAtual(pedidoItemExcluir.getProduto(), pedidoItemExcluir.getQuantidade(), true);
                totalCompra = totalCompra.subtract(pedidoItemExcluir.getValor());
//                texto_TotalCompra.setText(FormatUtils.formatBigDecimal(totalCompra));
                pedido.getItens().remove(pedidoItemExcluir);
                //DAOFactory.criaPedidoItemDAO().excluir(pedidoItemExcluir);
                if(CollectionUtils.isEmpty(pedido.getItens())) {
                    PedidoHelper.cancelaPedido(pedido);
                } else {
                   pedido = pedidoDAO.atualizar(pedido); 
                }
                reloadTable();
            } catch (ValidateException ex) {
                Logger.getLogger(PedidoForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_botao_ExcluirItemActionPerformed

    private void texto_codigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_codigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_codigoClienteActionPerformed

    private void texto_nomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_nomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_nomeClienteActionPerformed

    private void botao_pesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesquisarClienteActionPerformed
        ClienteBrowser cliente = (ClienteBrowser) GerenciadorJanelas.getInstance().abrirJanela(new ClienteBrowser());
        cliente.showWindow(this);
        cliente.setVisible(true);
    }//GEN-LAST:event_botao_pesquisarClienteActionPerformed

    private void botao_pesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pesquisarProdutoActionPerformed
        ProdutoBrowser produto = (ProdutoBrowser) GerenciadorJanelas.getInstance().abrirJanela(new ProdutoBrowser());
        produto.showWindow(this);
        produto.setVisible(true);
    }//GEN-LAST:event_botao_pesquisarProdutoActionPerformed

    private void botao_adicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_adicionarProdutoActionPerformed
        
    }//GEN-LAST:event_botao_adicionarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_CancelarPedido;
    private javax.swing.JButton botao_ExcluirItem;
    private javax.swing.JButton botao_FinalizaPedido;
    private javax.swing.JButton botao_adicionarProduto;
    private javax.swing.JButton botao_pesquisarCliente;
    private javax.swing.JButton botao_pesquisarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_PedidoItem;
    private javax.swing.JTextField texto_codigoCliente;
    private javax.swing.JTextField texto_codigoProduto;
    private javax.swing.JTextField texto_descricaoProduto;
    private javax.swing.JTextField texto_nomeCliente;
    private javax.swing.JTextField texto_observacao;
    private javax.swing.JFormattedTextField texto_quantidade;
    private javax.swing.JTextField texto_total;
    // End of variables declaration//GEN-END:variables

    public void adicionaProduto(Produto produto){
        if(StringUtils.isNotEmpty(texto_quantidade.getText()) && produto != null) {
            Integer quantidade = Integer.valueOf(texto_quantidade.getText());
            if(quantidade > 0) {
                try {
                    PedidoItem novoItem = new PedidoItem();
                    novoItem.setProduto(produto);
                    novoItem.setQuantidade(quantidade);
                    novoItem.setObservacao(texto_observacao.getText());
                    novoItem.setValor(produto.getValor());
                    if(CollectionUtils.isEmpty(pedido.getItens()))
                        pedido.setItens(new ArrayList<PedidoItem>());
                    
                    pedido.getItens().add(novoItem);
                    pedido = pedidoDAO.atualizar(pedido);
                    reloadTable();
                    atualizaTotalCompra();
                    texto_codigoProduto.setText("");
                    texto_quantidade.setText("1");
                    texto_observacao.setText("");
                } catch (ValidateException ex) {
                    Logger.getLogger(PedidoForm.class.getName()).log(Level.SEVERE, null, ex);
                    if(StringUtils.isNotEmpty(ex.getMessage()) && MensagemFixas.QUANTIDADE_INDISPONIVEL.toString().equals(ex.getMessage()) &&
                                                StringUtils.isNotEmpty(ex.getMensagemExcecao())) {
                            JOptionPane.showMessageDialog(this, ex.getMensagemExcecao(), "Erro!", JOptionPane.ERROR_MESSAGE);
                            texto_codigoProduto.setText(null);
                    } else {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                            texto_codigoProduto.setText(null);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Quantidade informada deve ser maior que zero!", "Erro!", JOptionPane.ERROR_MESSAGE);
                texto_quantidade.setText("1");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Para adicionar um produto, é necessário selecionar o produto e informar a quantidade.", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cancelaPedido() {
        
        try {
            PedidoHelper.cancelaPedido(pedido);
            limpar();
            JOptionPane.showMessageDialog(this, "Cancelamento realizado com sucesso!", "Cancelamento", JOptionPane.INFORMATION_MESSAGE);
        } catch (ValidateException ex) {
            Logger.getLogger(PedidoForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao cancelar!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limpar() {
        String bigDecimalZero = FormatUtils.formatBigDecimal(BigDecimal.ZERO);
        texto_codigoProduto.setText("");
//        texto_Quantidade.setText("1");
//        texto_Acrescimo.setText("");
//        texto_Desconto.setText("");
//        texto_TotalCompra.setText(bigDecimalZero);
//        texto_TotalRecebido.setText("");
//        texto_Troco.setText(bigDecimalZero);
//        textArea_Observacao.setText("");
        pedido = new Pedido();
        totalCompra = BigDecimal.ZERO;
        totalRecebido = BigDecimal.ZERO;
        reloadTable();
    }
    
    private void reloadTable() {
        PedidoItemTableModel modelo = (PedidoItemTableModel) tabela_PedidoItem.getModel();
        modelo.reload(pedido.getItens());
        tabela_PedidoItem.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabela_PedidoItem.setModel(modelo);
    }

    private PedidoItem getPedidoItemSelecionado() {
        if (tabela_PedidoItem.getSelectedRow() == -1)
            return null;
        
        PedidoItemTableModel modelo = (PedidoItemTableModel) tabela_PedidoItem.getModel();
        PedidoItem pedidoItemSelecionado = modelo.getPedidoItemAt(tabela_PedidoItem.getSelectedRow());
        return pedidoItemSelecionado;
    }

    @Override
    public void setSelecionado(Object obj) {
        if(obj != null) {
            if(obj instanceof Produto) {
                produtoLookup = (Produto) obj;
                texto_codigoProduto.setText(produtoLookup.getCodigo());
                texto_descricaoProduto.setText(produtoLookup.getDescricao());
            } else if(obj instanceof Cliente) {
                clienteLookup = (Cliente) obj;
                texto_codigoCliente.setText(clienteLookup.getCodigo());
                texto_nomeCliente.setText(clienteLookup.getNome());
            }
        }
       
    }

    private BigDecimal recuperaValorLucro() {
        if(CollectionUtils.isNotEmpty(pedido.getItens())) {
            BigDecimal valorLucro = BigDecimal.ZERO;
//            for (PedidoItem umProduto : pedido.getItens()) {
//                valorLucro = valorLucro.add(umProduto.getValor().subtract(umProduto.getValorCompra()));
//            }
//            valorLucro = valorLucro.subtract(pedido.getValorDesconto());
            return valorLucro;
        } else {
            return BigDecimal.ZERO;
        }
    }
    
    public void carregaPedido(Pedido pedidoCarregar){
        limpar();
        if(pedidoCarregar == null) {
            pedido = new Pedido();
        } else {
            try {
                pedido = pedidoDAO.buscar(pedidoCarregar.getId());
                reloadTable();
                atualizaTotalCompra();
            } catch (ValidateException ex) {
                Logger.getLogger(PedidoForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao buscar o pedido!", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }

    private void atualizaTotalCompra() {
        if(CollectionUtils.isNotEmpty(pedido.getItens())) {
            totalCompra = BigDecimal.ZERO;
            for (PedidoItem umItem : pedido.getItens()) {
                totalCompra = totalCompra.add(umItem.getValor());
            }
            //texto_TotalCompra.setText(FormatUtils.formatBigDecimal(totalCompra));
        }
    }

    private void onFocusTotalRecebido() {
        /*if(StringUtils.isNotEmpty(texto_TotalRecebido.getText())) {
           try {
                BigDecimal troco = BigDecimal.ZERO;
                BigDecimal desconto = BigDecimal.ZERO;
                totalRecebido = FormatUtils.parseBigDecimal(texto_TotalRecebido.getText()); //new BigDecimal(texto_TotalRecebido.getText().replaceAll(",", "."));
                if(totalRecebido.doubleValue() < 0) {
                    JOptionPane.showMessageDialog(this, "Não é possível informar um valor negativo!", "Erro!", JOptionPane.ERROR_MESSAGE);
                } else {
                    texto_Troco.setText(FormatUtils.formatBigDecimal(troco));
                    texto_Desconto.setText(FormatUtils.formatBigDecimal(desconto));
                    troco = totalRecebido.subtract(totalCompra);
                    if(troco.doubleValue() < 0) {
                        int resp = JOptionPane.showConfirmDialog(this, "O total recebido foi menor que o valor total da compra.\nDeseja utilizar o valor restando como desconto?");
                        if(resp == JOptionPane.YES_OPTION) {
                            desconto = troco.multiply(new BigDecimal(-1));
                            texto_Desconto.setText(FormatUtils.formatBigDecimal(desconto));
                        }
                    } else {
                        texto_Troco.setText(FormatUtils.formatBigDecimal(troco));
                    }
                }
           } catch (ParseException ex) {
               Logger.getLogger(PedidoForm.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
           }
        }*/
    }

}
