/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luismassaneiro.sistemadonai.view.operacoes;

import com.luismassaneiro.sistemadonai.controller.DAOFactory;
import com.luismassaneiro.sistemadonai.controller.PedidoDAO;
import com.luismassaneiro.sistemadonai.exceptions.ValidateException;
import com.luismassaneiro.sistemadonai.helper.PedidoHelper;
import com.luismassaneiro.sistemadonai.model.Pedido;
import com.luismassaneiro.sistemadonai.view.desktop.GerenciadorJanelas;
import com.luismassaneiro.sistemadonai.view.tablemodel.PedidoTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import org.apache.commons.collections.CollectionUtils;

/**
 *
 * @author luis.massaneiro
 */
public class PedidoBrowser extends javax.swing.JInternalFrame {

    private static final PedidoDAO pedidoDAO = DAOFactory.criaPedidoDAO();
    
    public PedidoBrowser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Pedido = new javax.swing.JTable();
        botao_FinalizaPedido = new javax.swing.JButton();
        botao_CancelarPedido = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Pedido pendentes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Os pedidos abaixo não foram finalizados, por favor selecione e informe o que deseja fazer:");

        tabela_Pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela_Pedido);

        botao_FinalizaPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botao_FinalizaPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/arrow-right-24.png"))); // NOI18N
        botao_FinalizaPedido.setText("Continuar");
        botao_FinalizaPedido.setMaximumSize(new java.awt.Dimension(141, 41));
        botao_FinalizaPedido.setMinimumSize(new java.awt.Dimension(141, 41));
        botao_FinalizaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_FinalizaPedidoActionPerformed(evt);
            }
        });

        botao_CancelarPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botao_CancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/cancel-24.png"))); // NOI18N
        botao_CancelarPedido.setText("Cancelar");
        botao_CancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CancelarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botao_FinalizaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_CancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_CancelarPedido)
                    .addComponent(botao_FinalizaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_FinalizaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_FinalizaPedidoActionPerformed
        if(getPedidoSelecionado() != null) {
            abrePedido(getPedidoSelecionado());
        }
    }//GEN-LAST:event_botao_FinalizaPedidoActionPerformed

    private void botao_CancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CancelarPedidoActionPerformed
        if(getPedidoSelecionado() != null) {
            int resp = JOptionPane.showConfirmDialog(this, "Os produtos que estão nesse pedido serão colocados novamento no estoque.\nDeseja realmente efetuar o cancelamento?");
            if(resp == JOptionPane.YES_OPTION) {
                cancelaPedido();
            }
        }
    }//GEN-LAST:event_botao_CancelarPedidoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        pesquisar();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_CancelarPedido;
    private javax.swing.JButton botao_FinalizaPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_Pedido;
    // End of variables declaration//GEN-END:variables
    
    private void cancelaPedido() {
        if(getPedidoSelecionado() != null) {
            try {
                Pedido pedido = getPedidoSelecionado();
                pedido = pedidoDAO.buscar(pedido.getId());
                PedidoHelper.cancelaPedido(pedido);
                JOptionPane.showMessageDialog(this, "Cancelamento realizado com sucesso!", "Cancelamento", JOptionPane.INFORMATION_MESSAGE);
                pesquisar();
            } catch (ValidateException ex) {
                Logger.getLogger(PedidoBrowser.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private Pedido getPedidoSelecionado() {
        if (tabela_Pedido.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum produto selecionado!", "Alerta", JOptionPane.WARNING_MESSAGE);
            return null;
        }   
        
        PedidoTableModel modelo = (PedidoTableModel) tabela_Pedido.getModel();
        Pedido pedidoSelecionado = modelo.getPedidoAt(tabela_Pedido.getSelectedRow());
        return pedidoSelecionado;
    }
    
    private void pesquisar() {
        PedidoTableModel modelo = new PedidoTableModel();
        List<Pedido> listaPedidos;
        try {
            listaPedidos = pedidoDAO.recuperaPedidoNaoFinalizados();
            if(CollectionUtils.isEmpty(listaPedidos)) {
                abrePedido(null);
            }
            modelo.reload(listaPedidos);
            tabela_Pedido.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tabela_Pedido.setModel(modelo);
        } catch (ValidateException ex) {
            Logger.getLogger(PedidoBrowser.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrePedido(Pedido pedidoSelecionado) {
        PedidoForm novoPedido = (PedidoForm) GerenciadorJanelas.getInstance().abrirJanela(new PedidoForm());
        novoPedido.carregaPedido(pedidoSelecionado);
        novoPedido.setVisible(true);
        hide();
    }
}   


