/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luismassaneiro.controleestoque.view.operacoes;

import com.luismassaneiro.controleestoque.controller.DAOFactory;
import com.luismassaneiro.controleestoque.controller.MovimentoEstoqueDAO;
import com.luismassaneiro.controleestoque.controller.ProdutoDAO;
import com.luismassaneiro.controleestoque.enums.MensagemFixas;
import com.luismassaneiro.controleestoque.exceptions.ValidateException;
import com.luismassaneiro.controleestoque.helper.ProdutoHelper;
import com.luismassaneiro.controleestoque.model.Produto;
import com.luismassaneiro.controleestoque.view.cadastro.ProdutoBrowser;
import com.luismassaneiro.controleestoque.view.Selecionador;
import com.luismassaneiro.controleestoque.view.desktop.GerenciadorJanelas;
import java.awt.KeyboardFocusManager;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author luis.massaneiro
 */
public class MovimentacaoEstoque extends javax.swing.JInternalFrame implements Selecionador<Produto> {

    private ProdutoDAO produtoDAO = DAOFactory.criaProdutoDAO();
    private MovimentoEstoqueDAO dao = DAOFactory.criaMovimentoEstoqueDAO();    
    private Produto produtoLookup;
    
    public MovimentacaoEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        texto_Descricao = new javax.swing.JTextField();
        radio_Saida = new javax.swing.JRadioButton();
        texto_Codigo = new javax.swing.JTextField();
        texto_Codigo.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, Collections.EMPTY_SET);
        radio_Entrada = new javax.swing.JRadioButton();
        texto_Quantidade = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botao_Pesquisa = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Movimentação de estoque");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Produto");

        buttonGroup1.add(radio_Saida);
        radio_Saida.setText("Saida");

        texto_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_CodigoActionPerformed(evt);
            }
        });
        texto_Codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                texto_CodigoKeyPressed(evt);
            }
        });

        buttonGroup1.add(radio_Entrada);
        radio_Entrada.setSelected(true);
        radio_Entrada.setText("Entrada");
        radio_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_EntradaActionPerformed(evt);
            }
        });

        texto_Quantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        texto_Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_QuantidadeActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/save.png"))); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade");

        botao_Pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luismassaneiro/controleestoque/imagens/search16.png"))); // NOI18N
        botao_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_PesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_Quantidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 318, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto_Descricao))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(radio_Entrada))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botao_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(radio_Saida)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_Entrada)
                    .addComponent(radio_Saida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(texto_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(texto_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botao_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_CodigoActionPerformed

    private void texto_CodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_CodigoKeyPressed
        if(evt.getKeyCode() == 9 || evt.getKeyCode() == 10) {
            if(StringUtils.isNotEmpty(texto_Codigo.getText())) {
                try {
                    produtoLookup = produtoDAO.recuperaProdutoPeloCodigo(texto_Codigo.getText());
                    if(produtoLookup != null) {
                        texto_Descricao.setText(produtoLookup.getDescricao());
                    } else {
                        JOptionPane.showMessageDialog(null, "Produto não encontrado!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ValidateException ex) {
                    Logger.getLogger(MovimentacaoEstoque.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Informe um código!", "Alerta!", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_texto_CodigoKeyPressed

    private void radio_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_EntradaActionPerformed

    private void texto_QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_QuantidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean podeGravar = true;
        Integer quantidade = 0;
        if(produtoLookup == null) {
            podeGravar = false;
            JOptionPane.showMessageDialog(null, "Produto não foi informado!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        if(StringUtils.isEmpty(texto_Quantidade.getText())) {
            podeGravar = false;
            JOptionPane.showMessageDialog(null, "É obrigatório informar a quantidade!", "Erro!", JOptionPane.ERROR_MESSAGE);
        } else {
            quantidade = Integer.valueOf(texto_Quantidade.getText());
        }

        try {
            if(radio_Saida.isSelected())
            ProdutoHelper.getInstance().verificaQuantidadeEmEstoque(produtoLookup, quantidade);

        } catch (ValidateException ex) {
            podeGravar = false;
            Logger.getLogger(MovimentacaoEstoque.class.getName()).log(Level.SEVERE, null, ex);
            if(StringUtils.isNotEmpty(ex.getMessage()) && MensagemFixas.QUANTIDADE_INDISPONIVEL.toString().equals(ex.getMessage()) &&
                StringUtils.isNotEmpty(ex.getMensagemExcecao())) {
                JOptionPane.showMessageDialog(this, ex.getMensagemExcecao(), "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }

        if(podeGravar) {
            try {
                ProdutoHelper.getInstance().atualizaQuantidadeAtual(produtoLookup, quantidade, radio_Entrada.isSelected());
                JOptionPane.showMessageDialog(this, "Movimentação realizada com sucesso!", "Finalização", JOptionPane.INFORMATION_MESSAGE);
                limpar();
            } catch (ValidateException ex) {
                Logger.getLogger(MovimentacaoEstoque.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botao_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_PesquisaActionPerformed
        ProdutoBrowser produto = (ProdutoBrowser) GerenciadorJanelas.getInstance().abrirJanela(new ProdutoBrowser());
        produto.showWindow(this);
        produto.setVisible(true);
    }//GEN-LAST:event_botao_PesquisaActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        texto_Quantidade.setText("");
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_Pesquisa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radio_Entrada;
    private javax.swing.JRadioButton radio_Saida;
    private javax.swing.JTextField texto_Codigo;
    private javax.swing.JTextField texto_Descricao;
    private javax.swing.JFormattedTextField texto_Quantidade;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        texto_Codigo.setText("");
        texto_Descricao.setText("");
        texto_Quantidade.setText("");
    }

    @Override
    public void setSelecionado(Produto produto) {
        if(produto != null) {
            produtoLookup = produto;
            texto_Codigo.setText(produto.getCodigo());
            texto_Descricao.setText(produto.getDescricao());
        }
    }
}
